name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: yarn install --frozen-lockfile
      run: yarn install --frozen-lockfile
      
    - name: yarn run cleantest
      run: yarn run cleantest

    - name: yarn run cleancoverage
      run: yarn run cleancoverage

#    - name: Coveralls
#      uses: coverallsapp/github-action@master
#      with:
#        path-to-lcov: ./docs/coverage/lcov.info
#        github-token: ${{ secrets.GITHUB_TOKEN }}
